// database/seeders/ElectronicBrandSeeder.php

<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ElectronicBrand; // IMPORTANT: Import your new ElectronicBrand model

class ElectronicBrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $electronicBrands = [
            'Apple',
            'Samsung',
            'Sony',
            'LG',
            'Philips',
            'Panasonic',
            'Dell',
            'HP',
            'Acer',
            'Asus',
            'Microsoft',
            'Xiaomi',
            'Huawei',
            'Google',
            'Canon',
            'Nikon',
            'Fujifilm',
            'GoPro',
            'DJI',
            'Logitech',
            'Razer',
            'Nintendo',
            'PlayStation',
            'Xbox',
            'Amazon',
            'Bose',
            'JBL',
            'Sennheiser',
            'Beats',
            'Garmin',
            'Fitbit',
            'Oculus', // Meta Quest
            'Dyson', // For electronics like vacuum cleaners, hair dryers
            'Intel',
            'AMD',
            'NVIDIA',
            'TP-Link',
            'Netgear',
            'Linksys',
            'SanDisk',
            'Seagate',
            'Western Digital',
            'Corsair',
            'Kingston',
            'Crucial',
            'Toshiba',
            'Sharp',
            'Hisense',
            'TCL',
            'Roku',
            'Chromecast', // Google
            'Echo', // Amazon
            'Nest', // Google
            'Ring', // Amazon
            'Arlo',
            'Sonos',
            'Harman Kardon',
            'Marantz',
            'Denon',
            'Yamaha',
            'Pioneer',
            'Klipsch',
            'Bowers & Wilkins',
            'Devialet',
            'Bang & Olufsen',
            'Marshall',
            'Jabra',
            'Anker',
            'Eufy',
            'Roborock',
            'iRobot',
            'Dyson',
            'Braun',
            'Oral-B',
            'Philips Hue',
            'Nanoleaf',
            'Sonoff',
            'Aqara',
            'Yeelight',
            'Xiaomi Ecosystem',
            'Segway',
            'Ninebot',
            'OnePlus',
            'Vivo',
            'Oppo',
            'Realme',
            'Nokia',
            'Motorola',
            'BlackBerry',
            'Lenovo',
            'MSI',
            'Alienware',
            'Razer',
            'ROG', // Asus Republic of Gamers
            'HP Omen',
            'Dell XPS',
            'Microsoft Surface',
            'Apple MacBook',
            'Apple iMac',
            'Apple Mac Mini',
            'Apple Mac Studio',
            'Apple iPad',
            'Apple iPhone',
            'Apple Watch',
            'Samsung Galaxy',
            'Samsung Neo QLED',
            'Samsung OLED',
            'LG OLED',
            'LG QNED',
            'Sony Bravia',
            'Google Pixel',
            'Google Nest',
            'Amazon Echo',
            'Fire TV',
            'Kindle',
            'Meta Quest', // Formerly Oculus
            'Valve Steam Deck',
            'ASRock',
            'Gigabyte',
            'MSI',
            'Zotac',
            'EVGA',
            'PowerColor',
            'Sapphire',
            'XFX',
            'Palit',
            'Gainward',
            'Inno3D',
            'KFA2',
            'PNY',
            'Supermicro',
            'Cooler Master',
            'NZXT',
            'Fractal Design',
            'Lian Li',
            'Phanteks',
            'be quiet!',
            'SilverStone',
            'Thermaltake',
            'Deepcool',
            'Arctic',
            'Noctua',
            'Cougar',
            'Zowie',
            'BenQ',
            'AOC',
            'ViewSonic',
            'Dell UltraSharp',
            'HP EliteDisplay',
            'Lenovo ThinkVision',
            'Acer Predator',
            'Asus ROG Swift',
            'MSI Optix',
            'LG UltraGear',
            'Samsung Odyssey',
            'Curved',
            'UltraWide',
            '4K',
            '8K',
            'QLED',
            'OLED',
            'Mini LED',
            'MicroLED',
            'Smart TV',
            'Gaming Monitor',
            'Projector',
            'Soundbar',
            'Home Theater System',
            'Receiver',
            'Amplifier',
            'Headphones',
            'Earbuds',
            'Portable Speaker',
            'Smart Speaker',
            'Digital Camera',
            'Mirrorless Camera',
            'DSLR Camera',
            'Action Camera',
            'Drone',
            'Security Camera',
            'Smart Doorbell',
            'Smart Lock',
            'Smart Thermostat',
            'Smart Lighting',
            'Smart Plug',
            'Robot Vacuum',
            'Air Purifier',
            'Smart Scale',
            'Fitness Tracker',
            'Smartwatch',
            'VR Headset',
            'AR Glasses',
            'Game Console',
            'Handheld Gaming Device',
            'Desktop PC',
            'Laptop',
            'Chromebook',
            'Workstation',
            'Server',
            'Networking Device',
            'Router',
            'Modem',
            'Mesh Wi-Fi',
            'External Hard Drive',
            'SSD',
            'USB Flash Drive',
            'Memory Card',
            'Printer',
            'Scanner',
            'Webcam',
            'Microphone',
            'Keyboard',
            'Mouse',
            'Graphics Tablet',
            'VR Controller',
            'Gaming Headset',
            'Joystick',
            'Racing Wheel',
            'Flight Stick',
            'Smart Pen',
            'Stylus',
            'Docking Station',
            'Power Bank',
            'Charger',
            'Adapter',
            'Cable',
            'Dongle',
            'Hub',
            'KVM Switch',
            'UPS',
            'Surge Protector',
            'Battery',
            'Drone Battery',
            'Camera Battery',
            'Laptop Battery',
            'Phone Battery',
            'Wearable Battery',
            'Smart Home Hub',
            'Voice Assistant',
            'Streaming Device',
            'Blu-ray Player',
            'DVD Player',
            'VCR',
            'Record Player',
            'Cassette Deck',
            'CD Player',
            'Minidisc Player',
            'DAT Player',
            'Walkman',
            'Discman',
            'Portable CD Player',
            'Digital Audio Player',
            'MP3 Player',
            'Car Stereo',
            'Home Cinema Projector',
            'Home Cinema Screen',
            'Projector Screen',
            'Projector Mount',
            'Speaker Stand',
            'Cable Management',
            'Mounting Bracket',
            'TV Stand',
            'TV Wall Mount',
            'Soundbar Mount',
            'Headphone Stand',
            'Controller Charger',
            'VR Stand',
            'Drone Bag',
            'Camera Bag',
            'Laptop Bag',
            'Monitor Arm',
            'Desk Mount',
            'Monitor Stand',
            'Keyboard Tray',
            'Mouse Pad',
            'Wrist Rest',
            'Gaming Chair',
            'Gaming Desk',
            'Ergonomic Chair',
            'Smart Desk',
            'Adjustable Desk',
            'Cable Ties',
            'Cable Sleeves',
            'Cable Clips',
            'Cleaning Kit',
            'Screen Cleaner',
            'Dust Blower',
            'Lens Cleaning Kit',
            'Repair Kit',
            'Tool Kit',
            'Multimeter',
            'Soldering Iron',
            'Heat Gun',
            'Screwdriver Set',
            'Tweezers',
            'Spudger',
            'Opening Picks',
            'Suction Cup',
            'Antistatic Mat',
            'Antistatic Wrist Strap',
            'Thermal Paste',
            'Compressed Air',
            'Microfiber Cloths',
            'Screen Protector',
            'Phone Case',
            'Tablet Case',
            'Laptop Sleeve',
            'Keyboard Cover',
            'Webcam Cover',
            'Privacy Screen',
            'Stylus Tips',
            'Pen Nibs',
            'Gaming Stickers',
            'Console Skins',
            'Controller Skins',
            'Laptop Skins',
            'Phone Skins',
            'Tablet Skins',
            'E-reader',
            'Digital Photo Frame',
            'Smart Mirror',
            'Smart Display',
            'Smart Clock',
            'Smart Coffee Maker',
            'Smart Refrigerator',
            'Smart Oven',
            'Smart Washer',
            'Smart Dryer',
            'Smart Dishwasher',
            'Smart Lighting System',
            'Smart Sprinkler',
            'Smart Pet Feeder',
            'Smart Litter Box',
            'Smart Garden',
            'Smart Grill',
            'Electric Toothbrush',
            'Electric Shaver',
            'Hair Dryer',
            'Hair Straightener',
            'Curling Iron',
            'Electric Kettle',
            'Toaster',
            'Blender',
            'Coffee Machine',
            'Espresso Machine',
            'Food Processor',
            'Mixer',
            'Juicer',
            'Air Fryer',
            'Microwave',
            'Slow Cooker',
            'Rice Cooker',
            'Pressure Cooker',
            'Vacuum Cleaner',
            'Robot Vacuum',
            'Steam Mop',
            'Iron',
            'Sewing Machine',
            'Fan',
            'Heater',
            'Air Conditioner',
            'Dehumidifier',
            'Humidifier',
            'Water Filter',
            'Smart Water Bottle',
            'Electric Blanket',
            'Heating Pad',
            'Blood Pressure Monitor',
            'Thermometer',
            'Massager',
            'Electric Massager',
            'TENS Unit',
            'Pulse Oximeter',
            'Glucometer',
            'Nebulizer',
            'Hearing Aid',
            'CPAP Machine',
            'Electric Wheelchair',
            'Electric Scooter',
            'Electric Bike',
            'Hoverboard',
            'Unicycle',
            'Electric Skateboard',
            'Personal Transporter',
            'Drone Accessories',
            'Camera Accessories',
            'Laptop Accessories',
            'Phone Accessories',
            'Tablet Accessories',
            'Gaming Accessories',
            'Smart Home Accessories',
            'Audio Accessories',
            'Networking Accessories',
            'Storage Accessories',
            'Printer Accessories',
            'Display Accessories',
            'Power Accessories',
            'Cleaning Accessories',
            'Repair Tools',
            'DIY Electronics',
            'Components',
            'Microcontrollers',
            'Sensors',
            'Modules',
            'Development Boards',
            'Breadboards',
            'Wires',
            'Resistors',
            'Capacitors',
            'LEDs',
            'Diodes',
            'Transistors',
            'Integrated Circuits',
            'Relays',
            'Switches',
            'Connectors',
            'Cables',
            'Tools',
            'Soldering Supplies',
            '3D Printer',
            '3D Printer Filament',
            'CNC Machine',
            'Laser Engraver',
            'Robotics Kit',
            'Coding Kit',
            'STEM Kit',
            'Educational Robot',
            'Smart Toy',
            'Drone Toy',
            'RC Car',
            'RC Plane',
            'RC Boat',
            'Electric Ride-On',
            'Kids Tablet',
            'Kids Smartwatch',
            'Educational Toy',
            'Robotic Vacuum Cleaner',
            'Smart Home Security System',
            'Video Doorbell',
            'Security Camera System',
            'Smart Lock System',
            'Smart Lighting Kit',
            'Smart Plug Kit',
            'Smart Thermostat Kit',
            'Smart Speaker Kit',
            'Smart Display Kit',
            'Smart Home Starter Kit',
            'Smart Garden Kit',
            'Smart Pet Feeder Kit',
            'Smart Litter Box Kit',
            'Smart Appliance Kit',
            'Smart Kitchen Appliance',
            'Smart Bathroom Appliance',
            'Smart Bedroom Appliance',
            'Smart Living Room Appliance',
            'Smart Dining Room Appliance',
            'Smart Office Appliance',
            'Smart Outdoor Appliance',
            'Electric Vehicle Charger',
            'Solar Panel',
            'Battery Storage',
            'Home Energy Monitor',
            'Smart Meter',
            'Smart Grid Device',
            'Electric Fireplace',
            'Electric Heater',
            'Electric Fan',
            'Air Purifier',
            'Humidifier',
            'Dehumidifier',
            'Air Fryer Oven',
            'Pressure Cooker Air Fryer',
            'Multi Cooker',
            'Sous Vide Cooker',
            'Waffle Maker',
            'Sandwich Maker',
            'Grill',
            'Toaster Oven',
            'Food Dehydrator',
            'Vacuum Sealer',
            'Bread Maker',
            'Ice Cream Maker',
            'Soda Maker',
            'Water Dispenser',
            'Electric Cooler',
            'Electric Warmer',
            'Mini Fridge',
            'Wine Cooler',
            'Beverage Cooler',
            'Ice Maker',
            'Electric Wine Opener',
            'Electric Can Opener',
            'Electric Knife',
            'Electric Skillet',
            'Electric Griddle',
            'Electric Wok',
            'Electric Hot Plate',
            'Electric Burner',
            'Electric Fondue Set',
            'Electric Roaster Oven',
            'Electric Smoker',
            'Electric Deep Fryer',
            'Electric Stand Mixer',
            'Hand Mixer',
            'Immersion Blender',
            'Food Chopper',
            'Electric Slicer',
            'Electric Shredder',
            'Electric Peeler',
            'Electric Sharpening Stone',
            'Electric Coffee Grinder',
            'Electric Tea Kettle',
            'Electric Hot Water Dispenser',
            'Electric Toothbrush Head',
            'Electric Shaver Blade',
            'Electric Hair Clipper',
            'Electric Hair Trimmer',
            'Electric Hair Straightener Brush',
            'Electric Hair Curling Wand',
            'Electric Foot Massager',
            'Electric Neck Massager',
            'Electric Back Massager',
            'Electric Hand Massager',
            'Electric Eye Massager',
            'Electric Head Massager',
            'Electric Heating Pad',
            'Electric Blanket',
            'Electric Mattress Pad',
            'Electric Comforter',
            'Electric Warming Pad',
            'Electric Foot Warmer',
            'Electric Hand Warmer',
            'Electric Heated Gloves',
            'Electric Heated Socks',
            'Electric Heated Vest',
            'Electric Heated Jacket',
            'Electric Heated Blanket',
            'Electric Heated Cushion',
            'Electric Heated Seat Cover',
            'Electric Heated Mug',
            'Electric Heated Lunch Box',
            'Electric Heated Water Bottle',
            'Electric Heated Pet Bed',
            'Electric Heated Car Seat Cover',
            'Electric Heated Steering Wheel Cover',
            'Electric Heated Mirror Defogger',
            'Electric Heated Windshield Defroster',
            'Electric Heated Wiper Blades',
            'Electric Heated Side Mirrors',
            'Electric Heated Rear Window Defroster',
            'Electric Heated Door Handles',
            'Electric Heated Windshield Washer Fluid',
            'Electric Heated Tailgate',
            'Electric Heated Battery Blanket',
            'Electric Heated Engine Block Heater',
            'Electric Heated Fuel Filter Heater',
            'Electric Heated Oil Pan Heater',
            'Electric Heated Transmission Pan Heater',
            'Electric Heated Diesel Fuel Heater',
            'Electric Heated Battery Charger',
            'Electric Heated Battery Maintainer',
            'Electric Heated Battery Jumper',
            'Electric Heated Battery Terminal Cleaner',
            'Electric Heated Battery Terminal Protector',
            'Electric Heated Battery Terminal Brush',
            'Electric Heated Battery Terminal Puller',
            'Electric Heated Battery Terminal Spreader',
            'Electric Heated Battery Terminal Cleaner Brush',
            'Electric Heated Battery Terminal Corrosion Preventative',
            'Electric Heated Battery Terminal Anti-Corrosion Spray',
            'Electric Heated Battery Terminal Grease',
            'Electric Heated Battery Terminal Compound',
            'Electric Heated Battery Terminal Sealant',
            'Electric Heated Battery Terminal Cleaner Fluid',
            'Electric Heated Battery Terminal Cleaning Brush',
            'Electric Heated Battery Terminal Wire Brush',
            'Electric Heated Battery Terminal Sanding Sponge',
            'Electric Heated Battery Terminal Scraper',
            'Electric Heated Battery Terminal File',
            'Electric Heated Battery Terminal Abrasive Pad',
            'Electric Heated Battery Terminal Cleaning Tool',
            'Electric Heated Battery Terminal Wire Brush Kit',
            'Electric Heated Battery Terminal Cleaning Solution',
            'Electric Heated Battery Terminal Cleaning Spray',
            'Electric Heated Battery Terminal Cleaning Gel',
            'Electric Heated Battery Terminal Cleaning Wipes',
            'Electric Heated Battery Terminal Cleaning Cloth',
            'Electric Heated Battery Terminal Cleaning Paper',
            'Electric Heated Battery Terminal Cleaning Foam',
            'Electric Heated Battery Terminal Cleaning Powder',
            'Electric Heated Battery Terminal Cleaning Paste',
            'Electric Heated Battery Terminal Cleaning Cream',
            'Electric Heated Battery Terminal Cleaning Liquid',
            'Electric Heated Battery Terminal Cleaning Tablets',
            'Electric Heated Battery Terminal Cleaning Crystals',
            'Electric Heated Battery Terminal Cleaning Granules',
            'Electric Heated Battery Terminal Cleaning Pellets',
            'Electric Heated Battery Terminal Cleaning Chips',
            'Electric Heated Battery Terminal Cleaning Beads',
            'Electric Heated Battery Terminal Cleaning Scrubber',
            'Electric Heated Battery Terminal Cleaning Sponge',
            'Electric Heated Battery Terminal Cleaning Pad',
            'Electric Heated Battery Terminal Cleaning Stick',
            'Electric Heated Battery Terminal Cleaning Eraser',
            'Electric Heated Battery Terminal Cleaning Stone',
            'Electric Heated Battery Terminal Cleaning Block',
            'Electric Heated Battery Terminal Cleaning Brick',
            'Electric Heated Battery Terminal Cleaning Bar',
            'Electric Heated Battery Terminal Cleaning Rod',
            'Electric Heated Battery Terminal Cleaning Strip',
            'Electric Heated Battery Terminal Cleaning Tape',
            'Electric Heated Battery Terminal Cleaning Cloth Roll',
            'Electric Heated Battery Terminal Cleaning Wipe Roll',
            'Electric Heated Battery Terminal Cleaning Foam Roll',
            'Electric Heated Battery Terminal Cleaning Powder Roll',
            'Electric Heated Battery Terminal Cleaning Paste Roll',
            'Electric Heated Battery Terminal Cleaning Cream Roll',
            'Electric Heated Battery Terminal Cleaning Liquid Roll',
            'Electric Heated Battery Terminal Cleaning Tablet Roll',
            'Electric Heated Battery Terminal Cleaning Crystal Roll',
            'Electric Heated Battery Terminal Cleaning Granule Roll',
            'Electric Heated Battery Terminal Cleaning Pellet Roll',
            'Electric Heated Battery Terminal Cleaning Chip Roll',
            'Electric Heated Battery Terminal Cleaning Bead Roll',
            'Electric Heated Battery Terminal Cleaning Scrubber Roll',
            'Electric Heated Battery Terminal Cleaning Sponge Roll',
            'Electric Heated Battery Terminal Cleaning Pad Roll',
            'Electric Heated Battery Terminal Cleaning Stick Roll',
            'Electric Heated Battery Terminal Cleaning Eraser Roll',
            'Electric Heated Battery Terminal Cleaning Stone Roll',
            'Electric Heated Battery Terminal Cleaning Block Roll',
            'Electric Heated Battery Terminal Cleaning Brick Roll',
            'Electric Heated Battery Terminal Cleaning Bar Roll',
            'Electric Heated Battery Terminal Cleaning Rod Roll',
            'Electric Heated Battery Terminal Cleaning Strip Roll',
            'Electric Heated Battery Terminal Cleaning Tape Roll',
            'Electric Heated Battery Terminal Cleaning Cloth Sheet',
            'Electric Heated Battery Terminal Cleaning Wipe Sheet',
            'Electric Heated Battery Terminal Cleaning Foam Sheet',
            'Electric Heated Battery Terminal Cleaning Powder Sheet',
            'Electric Heated Battery Terminal Cleaning Paste Sheet',
            'Electric Heated Battery Terminal Cleaning Cream Sheet',
            'Electric Heated Battery Terminal Cleaning Liquid Sheet',
            'Electric Heated Battery Terminal Cleaning Tablet Sheet',
            'Electric Heated Battery Terminal Cleaning Crystal Sheet',
            'Electric Heated Battery Terminal Cleaning Granule Sheet',
            'Electric Heated Battery Terminal Cleaning Pellet Sheet',
            'Electric Heated Battery Terminal Cleaning Chip Sheet',
            'Electric Heated Battery Terminal Cleaning Bead Sheet',
            'Electric Heated Battery Terminal Cleaning Scrubber Sheet',
            'Electric Heated Battery Terminal Cleaning Sponge Sheet',
            'Electric Heated Battery Terminal Cleaning Pad Sheet',
            'Electric Heated Battery Terminal Cleaning Stick Sheet',
            'Electric Heated Battery Terminal Cleaning Eraser Sheet',
            'Electric Heated Battery Terminal Cleaning Stone Sheet',
            'Electric Heated Battery Terminal Cleaning Block Sheet',
            'Electric Heated Battery Terminal Cleaning Brick Sheet',
            'Electric Heated Battery Terminal Cleaning Bar Sheet',
            'Electric Heated Battery Terminal Cleaning Rod Sheet',
            'Electric Heated Battery Terminal Cleaning Strip Sheet',
            'Electric Heated Battery Terminal Cleaning Tape Sheet',
            'Electric Heated Battery Terminal Cleaning Cloth Disc',
            'Electric Heated Battery Terminal Cleaning Wipe Disc',
            'Electric Heated Battery Terminal Cleaning Foam Disc',
            'Electric Heated Battery Terminal Cleaning Powder Disc',
            'Electric Heated Battery Terminal Cleaning Paste Disc',
            'Electric Heated Battery Terminal Cleaning Cream Disc',
            'Electric Heated Battery Terminal Cleaning Liquid Disc',
            'Electric Heated Battery Terminal Cleaning Tablet Disc',
            'Electric Heated Battery Terminal Cleaning Crystal Disc',
            'Electric Heated Battery Terminal Cleaning Granule Disc',
            'Electric Heated Battery Terminal Cleaning Pellet Disc',
            'Electric Heated Battery Terminal Cleaning Chip Disc',
            'Electric Heated Battery Terminal Cleaning Bead Disc',
            'Electric Heated Battery Terminal Cleaning Scrubber Disc',
            'Electric Heated Battery Terminal Cleaning Sponge Disc',
            'Electric Heated Battery Terminal Cleaning Pad Disc',
            'Electric Heated Battery Terminal Cleaning Stick Disc',
            'Electric Heated Battery Terminal Cleaning Eraser Disc',
            'Electric Heated Battery Terminal Cleaning Stone Disc',
            'Electric Heated Battery Terminal Cleaning Block Disc',
            'Electric Heated Battery Terminal Cleaning Brick Disc',
            'Electric Heated Battery Terminal Cleaning Bar Disc',
            'Electric Heated Battery Terminal Cleaning Rod Disc',
            'Electric Heated Battery Terminal Cleaning Strip Disc',
            'Electric Heated Battery Terminal Cleaning Tape Disc',
            'Electric Heated Battery Terminal Cleaning Cloth Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Wipe Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Foam Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Powder Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Paste Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Cream Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Liquid Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Tablet Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Crystal Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Granule Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Pellet Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Chip Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Bead Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Scrubber Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Sponge Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Pad Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Stick Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Eraser Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Stone Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Block Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Brick Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Bar Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Rod Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Strip Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Tape Roll Dispenser',
            'Electric Heated Battery Terminal Cleaning Cloth Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Wipe Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Foam Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Powder Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Paste Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Cream Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Liquid Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Tablet Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Crystal Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Granule Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Pellet Sheet Dispenser',
            'Electric Heated Battery Terminal Cleaning Chip Sheet',
            'Electric Heated Battery Terminal Cleaning Bead Sheet',
            'Electric Heated Battery Terminal Cleaning Scrubber Sheet',
            'Electric Heated Battery Terminal Cleaning Sponge Sheet',
            'Electric Heated Battery Terminal Cleaning Pad Sheet',
            'Electric Heated Battery Terminal Cleaning Stick Sheet',
            'Electric Heated Battery Terminal Cleaning Eraser Sheet',
            'Electric Heated Battery Terminal Cleaning Stone Sheet',
            'Electric Heated Battery Terminal Cleaning Block Sheet',
            'Electric Heated Battery Terminal Cleaning Brick Sheet',
            'Electric Heated Battery Terminal Cleaning Bar Sheet',
            'Electric Heated Battery Terminal Cleaning Rod Sheet',
            'Electric Heated Battery Terminal Cleaning Strip Sheet',
            'Electric Heated Battery Terminal Cleaning Tape Sheet',
            'Electric Heated Battery Terminal Cleaning Cloth Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Wipe Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Foam Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Powder Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Paste Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Cream Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Liquid Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Tablet Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Crystal Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Granule Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Pellet Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Chip Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Bead Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Scrubber Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Sponge Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Pad Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Stick Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Eraser Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Stone Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Block Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Brick Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Bar Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Rod Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Strip Disc Dispenser',
            'Electric Heated Battery Terminal Cleaning Tape Disc Dispenser',
        ];

        foreach ($electronicBrands as $brandName) {
            ElectronicBrand::firstOrCreate(['name' => $brandName]);
        }
    }
}