<?php // This should be the very first line of actual code

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ElectronicBrand; // IMPORTANT: Import your new ElectronicBrand model

class ElectronicBrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // This is a curated list of well-known electronic brands.
        // It has been updated to remove product lines, duplicates, and generic product types.
        $electronicBrands = [
            'Apple',
            'Samsung',
            'Sony',
            'LG',
            'Philips',
            'Panasonic',
            'Dell',
            'HP',
            'Acer',
            'Asus',
            'Microsoft',
            'Xiaomi',
            'Huawei',
            'Google',
            'Canon',
            'Nikon',
            'Fujifilm',
            'GoPro',
            'DJI',
            'Logitech',
            'Razer',
            'Nintendo',
            'PlayStation',
            'Xbox',
            'Amazon',
            'Bose',
            'JBL',
            'Sennheiser',
            'Beats',
            'Garmin',
            'Fitbit',
            'Oculus',
            'Meta',
            'Dyson',
            'Intel',
            'AMD',
            'NVIDIA',
            'TP-Link',
            'Netgear',
            'Linksys',
            'SanDisk',
            'Seagate',
            'Western Digital',
            'Corsair',
            'Kingston',
            'Crucial',
            'Toshiba',
            'Sharp',
            'Hisense',
            'TCL',
            'Roku',
            'Sonos',
            'Harman Kardon',
            'Marantz',
            'Denon',
            'Yamaha',
            'Pioneer',
            'Klipsch',
            'Bowers & Wilkins',
            'Devialet',
            'Bang & Olufsen',
            'Marshall',
            'Jabra',
            'Anker',
            'Eufy',
            'Roborock',
            'iRobot',
            'Braun',
            'Oral-B',
            'Nanoleaf',
            'Sonoff',
            'Aqara',
            'Yeelight',
            'OnePlus',
            'Vivo',
            'Oppo',
            'Realme',
            'Nokia',
            'Motorola',
            'BlackBerry',
            'Lenovo',
            'MSI',
            'ASRock',
            'Gigabyte',
            'Zotac',
            'EVGA',
            'PowerColor',
            'Sapphire',
            'XFX',
            'Palit',
            'Gainward',
            'Inno3D',
            'KFA2',
            'PNY',
            'Supermicro',
            'Cooler Master',
            'NZXT',
            'Fractal Design',
            'Lian Li',
            'Phanteks',
            'be quiet!',
            'SilverStone',
            'Thermaltake',
            'Deepcool',
            'Arctic',
            'Noctua',
            'Cougar',
            'Zowie',
            'BenQ',
            'AOC',
            'ViewSonic',
            'Other',
        ];

        foreach ($electronicBrands as $brandName) {
            ElectronicBrand::firstOrCreate(['name' => $brandName]);
        }
    }
}
